Make it possible not to link against libsystemd
heftig/rtkit pull request #14
Opened 2020-03-13 13:59 UTC by mkszuba

This PR adds a configure option --disable-systemd-integration, which allows anyone who does not wish rtkit to use the sd-daemon API (_e.g._ Gentoo users who have chosen to stick with OpenRC as their init system) not to link it against libsystemd.

rtkit is very important _e.g._ for having PulseAudio sound work properly even under high system load and while I personally am a huge fan of systemd, I see no reason to deny access to newer rtkit versions to users of other init systems.

2020-03-13 14:11 UTC, heftig commented
Thanks. Please also modify the meson build.

2020-03-13 14:15 UTC, mkszuba commented
I'll try but it might take a while because I'll have to actually learn meson in the process :-) Will keep you posted!

2020-03-16 13:28 UTC, mkszuba commented
Okay, that has taken rather less time than I anticipated. Here you go! Seems to do what it is supposed to, i.e. be functionally identical to autoconf changes.

2020-03-20 14:57 UTC, heftig commented
Sorry, I've been a bit busy with work and I'll do a review this weekend.

2020-03-22 16:12 UTC, heftig requested changes

2020-03-22 16:12 UTC, heftig commented on meson_options.txt
> +)
Please rename this option to `'libsystemd'`.

Also make it a feature option: `type: 'feature', value: 'auto'`; you can then pass it directly to `dependency`'s `required` argument in order to get a dependency that is ignored, optional or required, depending on the setting.

```meson
libsystemd_dep = dependency('libsystemd', required: get_option('libsystemd'))
```
```meson
config.set('HAVE_LIBSYSTEMD', libsystemd_dep.found())
```

2020-03-22 16:12 UTC, heftig commented on configure.ac
> +fi
Please rename the argument to `libsystemd` (i.e. `--enable-libsystemd`/`--disable-libsystemd`).

Also make it default to automatic detection, so that a missing argument means the library will be used if and only if it is present. Unfortunately, I don't recall the autoconf magic to do that.

2020-03-22 20:14 UTC, heftig commented on configure.ac
> +fi
Great, thanks! That just leaves the autodetection on the autoconf side.

2020-03-23 06:13 UTC, heftig approved these changes
Thanks!

2020-03-23 06:14 UTC, merged